### ISSUE TITLE
How to get Action on subscription

### ISSUE THREAD

**Issue by Mx-Iris** [Swift-Flow/Swift-Flow#514] opened 2024-08-06 14:34 UTC
I want to get which action made the change when subscribing, e.g. if I change the value of a cell, I want to reload that cell individually instead of reloading the whole tableview.

**Comment by DivineDominion** [comment] 2024-08-06 14:51
If you need this information, the best place is actually in your state. Like replacing `value: TheValue` with `value: (TheValue, ChangeReason)`, basically.

-------

That being said, the example you mention sounds like you could optimize for per-cell changes with either (spitballing ideas here)

- diffing the state on a state change, and then acting on the difference (which should be of the form "cell X,Y changed")
- putting cell changes onto a queue for the UI to consume, like `pendingCellChanges: [(coord: CellCoordinate, value: TheValue)]`; then have an action `append` to that array, and when the UI has consumed the `first` element, emit another action to remove the first element form the queue, and do this until `pendingCellChanges` is empty

**Comment by Mx-Iris** [comment] 2024-08-06 15:35
@DivineDominion 

Thank you for your answer. 

It would be even better if I could directly get the action, as it contains the information I need to refresh the UI. 

In my tableView, each cell has a status. If the status changes, I only need to refresh that particular cell. Additionally, updating the selected status does not require reloading the entire tableView. Some refresh logic is specific to certain operations.

I think I can try the second method you mentioned.

**Comment by DivineDominion** [comment] 2024-08-06 18:35
If you absolutely need the action, store it as "last action" in your state. That's an odd approach, though. I know that it can be weird to duplicate all the action's information in the state, but that's the design of the framework and its unidirectional flow :) It scales really well, though. 

If you want something more like Flux.js (which uses per-component wiring, instead of a global app state) you can try pointfree's The Composable Architecture components instead.

**Comment by DivineDominion** [comment] 2024-08-07 07:54
Closing the issue itself because it's a usage question, not a bug/issue with the framework. Feel free to continue discussing.

**Closed as not planned by DivineDominion** 2024-08-07 07:54 UTC

**Comment by Mx-Iris** [comment] 2024-08-07 12:22
@DivineDominion OK, I see. Thank you for your answer
